server:
  port: 8090


spring:
    datasource:
        name: mysql_test
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.jdbc.Driver
          #基本属性
          url: jdbc:mysql://rm-bp1fka7dq724021579o.mysql.rds.aliyuncs.com:3306/zpno1?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
          username: yhl
          password: yhl@2022
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
    thymeleaf:
            prefix: classpath:/templates/
            check-template-location: true
            suffix: .html
            encoding: UTF-8
            mode: LEGACYHTML5
            cache: false
    aop:
      auto: true
      proxy-target-class: true
    servlet:
          multipart:
            max-file-size: 10Mb
            max-request-size: 100Mb


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.luischen.model


#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

logging:
  level:
    cn.drose.dao : DEBUG

swagger:
  show: true


#qiniu:
#  accesskey: "rYvCVLjVyyGLE2WgviKp10sRXKGUJbGrX22urL4W"
#  serectkey: "OzUVxnMK2Tj2W-2tk6BcmmxdwE7tfyiSMiJATpXS"
#  bucket: "qqemail-zp"
#  cdn:
#    url: "qleyiopvu.hd-bkt.clouddn.com/"
qiniu:
  accesskey: "paWCYuCarLFbl4uv8DATd8KLcbG3clogDOijz5q1"
  serectkey: "Q-f8sDCKMx4JLO2CBtjnCdG6gyxu_PZBrtu1fOJG"
  bucket: "yhl-cv"
  cdn:
    url: "yhlssh.top/"

upload:
  url: https://api.github.com/repos/374362356/github_images/contents
  profiles: /main
  path: /img/test/
  cdnurl: https://cdn.jsdelivr.net/gh/374362356/github_images
  flag: 1